name: StigglesLearn
version: '${project.version}'
main: com.stigglespatch.main.Main
api-version: 1.19
authors: [ Accnt ]
commands:
  dungeon:
    description: For admins.
  smp:
    description: For admins only.
  creative:
    description: For admins- only.
  dp:
    description: Allows you to make a party to raid a dungeon.
    aliases: dungeon_party
  start-dungeon:
    description: idk
  check:
    description: hmmm
  get-items:
    description: a
  strayGroup:
    description: b

